spring:
  application:
    name: server

server:
  port: 19090

eureka:
  client:
    register-with-eureka: false # ?? Eureka ??? ? ??? ???? ??
    fetch-registry: false # ?? Eureka ??? ?????? ???? ??
    service-url:
      defalutZone: http://localhost:19090/eureka/
  instance:
    hostname: localhost