server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: product-service1
          uri: http://localhost:19093
          predicates:
            - Path=/products/**
            - Weight=group1,7
        - id: product-service2
          uri: http://localhost:19094
          predicates:
            - Path=/products/**
            - Weight=group1,3
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
      discovery:
        locator:
          enabled: true

service:
  jwt:
    access-expiration: 3600000
    secret-key: ${SECRET_KEY}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/