server:
  port: 19091

spring:
  main:
    web-application-type: reactive  # Spring ??????? ???? ? ???????? ???
  application:
    name: gateway-service  # ?????? ??? 'gateway-service'? ??
  cloud:
    gateway:
      routes:  # Spring Cloud Gateway? ??? ??
        - id: order-service  # ??? ???
          uri: lb://order-service  # 'order-service'?? ???? ?? ???? ???? ???
          predicates:
            - Path=/orders/**  # /order/** ??? ???? ??? ? ???? ??
        - id: product-service  # ??? ???
          uri: lb://product-service  # 'product-service'?? ???? ?? ???? ???? ???
          predicates:
            - Path=/products/**  # /product/** ??? ???? ??? ? ???? ??
        - id: auth-service  # ??? ???
          uri: lb://auth-service  # 'auth-service'?? ???? ?? ???? ???? ???
          predicates:
            - Path=/auth/**  # /auth/signIn ??? ???? ??? ? ???? ??
      discovery:
        locator:
          enabled: true  # ??? ?????? ?? ???? ???? ????? ??

service:
  jwt:
    access-expiration: 3600000
    secret-key: ${SECRET_KEY}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka ??? URL? ??
